name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build g++

      - name: Configure build
        run: meson setup build

      - name: Build
        run: meson compile -C build

      - name: Test
        run: meson test -C build
